function buildResponseMessage(catchedError) {
  return catchedError ? catchedError : "Entidade excluÃ­da com sucesso";
}

export default (deletionWasSuccessful, catchedError) => {
  return {
    success: deletionWasSuccessful,
    message: buildResponseMessage(catchedError)
  };
};
